

# Sección para definir los diferentes servicios (contenedores) de tu aplicación
services:
  ui:
    build: ./ui
    container_name: vue_frontend
    # Mapea el puerto 5173 del host al puerto 5173 del contenedor de Vite
    ports:
      - "5173:5173" 
    depends_on:
      - core
    environment:
      # Pasa la URL del backend al contenedor del frontend
      VUE_APP_BACKEND_URL: http://core:8080 
      VITE_PORT: 5173 

  # Define el servicio del backend (tu aplicación C++)
  core:
    # Indica a Docker Compose que construya la imagen a partir de un Dockerfile
    build:
      # El contexto de construcción es la ruta a tu directorio 'core'
      context: ./core
      # El Dockerfile a usar para construir la imagen del backend
      dockerfile: Dockerfile
    # Asigna un nombre específico al contenedor para facilitar su identificación
    container_name: cpp_backend
    # Mapea los puertos del host a los puertos del contenedor
    # "8080:8080" significa que el puerto 8080 de tu máquina (host) se mapea al puerto 8080 del contenedor
    # Esto te permitirá acceder a tu API de C++ en http://localhost:8080
    ports:
      - "8080:8080"