# Sección para definir los diferentes servicios (contenedores) de tu aplicación
services:
  ui:
    build: ./ui
    container_name: vue_frontend
    # Mapea el puerto 5173 del host al puerto 5173 del contenedor de Vite
    ports:
      - "5173:5173"
    depends_on:
      - core
    environment:
      # Pasa la URL del backend al contenedor del frontend
      VUE_APP_BACKEND_URL: http://core:8081
      VITE_PORT: 5173

  # Define el servicio del backend (tu aplicación C++)
  core:
    # Indica a Docker Compose que construya la imagen a partir de un Dockerfile
    build:
      # El contexto de construcción es la ruta a tu directorio 'core'
      context: ./core
      # El Dockerfile a usar para construir la imagen del backend
      dockerfile: Dockerfile
    # Asigna un nombre específico al contenedor para facilitar su identificación
    container_name: cpp_backend
    # Mapea los puertos del host a los puertos del contenedor
    ports:
      - "8081:8081"
